### ISSUE TITLE
an unexpected keyword argument 'rope_theta'

### ISSUE THREAD

**Issue by mietekrmd** [hkproj/pytorch-llama#4]
Hi, After running the download script, I pasted the URL from the email and encountered the following errors in my terminal:
```
Enter the URL from email: https://download.llamameta.net/*?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoid2p5eTF5YjQwZDRxYXJwZWc5ZXhxaHE2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMDQ5OTQxM319fV19&Signature=PHLzzsM%7EBsX9EzzxAH1MbEzQjBWoMf4OM%7Eb7M0-auOub1jEBXL8X3xbJx24uaKGrCC-6VLPyjqpReHVcRkNOt6IH543eeypZwAgSH9io7P-Q-JQGKjHaXYjgD0A8n6330VRC07wQGC9VU1Lv%7E0RzpZDdPMtfkrEas3W9bLUTfE0BlxY5ilvpcHDSuAFwtQk6MP0AlzLSiqzQQCc0Bj93rn6F%7EG0VKgkN8LAc6Z%7EYP3%7E2ZtuWo5KuoUsqXujB7UnzZTlrW3ZR5ODVWUB%7Ed6AWHlh7KLtczSKJTtLaC6vBOE0Tt9XFwX0sFazctlizlf-s6AQn26tMi0WryOQVXvrOGg__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1361551944476193

Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 7b
Downloading LICENSE and Acceptable Usage Policy
--2023-11-20 23:25:33--  https://download.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoid2p5eTF5YjQwZDRxYXJwZWc5ZXhxaHE2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMDQ5OTQxM319fV19&Signature=PHLzzsM%7EBsX9EzzxAH1MbEzQjBWoMf4OM%7Eb7M0-auOub1jEBXL8X3xbJx24uaKGrCC-6VLPyjqpReHVcRkNOt6IH543eeypZwAgSH9io7P-Q-JQGKjHaXYjgD0A8n6330VRC07wQGC9VU1Lv%7E0RzpZDdPMtfkrEas3W9bLUTfE0BlxY5ilvpcHDSuAFwtQk6MP0AlzLSiqzQQCc0Bj93rn6F%7EG0VKgkN8LAc6Z%7EYP3%7E2ZtuWo5KuoUsqXujB7UnzZTlrW3ZR5ODVWUB%7Ed6AWHlh7KLtczSKJTtLaC6vBOE0Tt9XFwX0sFazctlizlf-s6AQn26tMi0WryOQVXvrOGg__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1361551944476193
Resolving download.llamameta.net (download.llamameta.net)... 108.138.51.32, 108.138.51.79, 108.138.51.128, ...
Connecting to download.llamameta.net (download.llamameta.net)|108.138.51.32|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-20 23:25:33 ERROR 403: Forbidden.

--2023-11-20 23:25:33--  https://download.llamameta.net/USE_POLICY.md?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoid2p5eTF5YjQwZDRxYXJwZWc5ZXhxaHE2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMDQ5OTQxM319fV19&Signature=PHLzzsM%7EBsX9EzzxAH1MbEzQjBWoMf4OM%7Eb7M0-auOub1jEBXL8X3xbJx24uaKGrCC-6VLPyjqpReHVcRkNOt6IH543eeypZwAgSH9io7P-Q-JQGKjHaXYjgD0A8n6330VRC07wQGC9VU1Lv%7E0RzpZDdPMtfkrEas3W9bLUTfE0BlxY5ilvpcHDSuAFwtQk6MP0AlzLSiqzQQCc0Bj93rn6F%7EG0VKgkN8LAc6Z%7EYP3%7E2ZtuWo5KuoUsqXujB7UnzZTlrW3ZR5ODVWUB%7Ed6AWHlh7KLtczSKJTtLaC6vBOE0Tt9XFwX0sFazctlizlf-s6AQn26tMi0WryOQVXvrOGg__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1361551944476193
Resolving download.llamameta.net (download.llamameta.net)... 108.138.51.32, 108.138.51.79, 108.138.51.128, ...
Connecting to download.llamameta.net (download.llamameta.net)|108.138.51.32|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-20 23:25:33 ERROR 403: Forbidden.

Downloading tokenizer
--2023-11-20 23:25:33--  https://download.llamameta.net/tokenizer.model?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoid2p5eTF5YjQwZDRxYXJwZWc5ZXhxaHE2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMDQ5OTQxM319fV19&Signature=PHLzzsM%7EBsX9EzzxAH1MbEzQjBWoMf4OM%7Eb7M0-auOub1jEBXL8X3xbJx24uaKGrCC-6VLPyjqpReHVcRkNOt6IH543eeypZwAgSH9io7P-Q-JQGKjHaXYjgD0A8n6330VRC07wQGC9VU1Lv%7E0RzpZDdPMtfkrEas3W9bLUTfE0BlxY5ilvpcHDSuAFwtQk6MP0AlzLSiqzQQCc0Bj93rn6F%7EG0VKgkN8LAc6Z%7EYP3%7E2ZtuWo5KuoUsqXujB7UnzZTlrW3ZR5ODVWUB%7Ed6AWHlh7KLtczSKJTtLaC6vBOE0Tt9XFwX0sFazctlizlf-s6AQn26tMi0WryOQVXvrOGg__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1361551944476193
Resolving download.llamameta.net (download.llamameta.net)... 108.138.51.32, 108.138.51.79, 108.138.51.128, ...
Connecting to download.llamameta.net (download.llamameta.net)|108.138.51.32|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-20 23:25:33 ERROR 403: Forbidden.

--2023-11-20 23:25:33--  https://download.llamameta.net/tokenizer_checklist.chk?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoid2p5eTF5YjQwZDRxYXJwZWc5ZXhxaHE2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMDQ5OTQxM319fV19&Signature=PHLzzsM%7EBsX9EzzxAH1MbEzQjBWoMf4OM%7Eb7M0-auOub1jEBXL8X3xbJx24uaKGrCC-6VLPyjqpReHVcRkNOt6IH543eeypZwAgSH9io7P-Q-JQGKjHaXYjgD0A8n6330VRC07wQGC9VU1Lv%7E0RzpZDdPMtfkrEas3W9bLUTfE0BlxY5ilvpcHDSuAFwtQk6MP0AlzLSiqzQQCc0Bj93rn6F%7EG0VKgkN8LAc6Z%7EYP3%7E2ZtuWo5KuoUsqXujB7UnzZTlrW3ZR5ODVWUB%7Ed6AWHlh7KLtczSKJTtLaC6vBOE0Tt9XFwX0sFazctlizlf-s6AQn26tMi0WryOQVXvrOGg__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1361551944476193
Resolving download.llamameta.net (download.llamameta.net)... 108.138.51.32, 108.138.51.79, 108.138.51.128, ...
Connecting to download.llamameta.net (download.llamameta.net)|108.138.51.32|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-20 23:25:33 ERROR 403: Forbidden.

md5sum: tokenizer_checklist.chk: no properly formatted checksum lines found
Downloading
--2023-11-20 23:25:33--  https://download.llamameta.net//params.json?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoid2p5eTF5YjQwZDRxYXJwZWc5ZXhxaHE2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMDQ5OTQxM319fV19&Signature=PHLzzsM%7EBsX9EzzxAH1MbEzQjBWoMf4OM%7Eb7M0-auOub1jEBXL8X3xbJx24uaKGrCC-6VLPyjqpReHVcRkNOt6IH543eeypZwAgSH9io7P-Q-JQGKjHaXYjgD0A8n6330VRC07wQGC9VU1Lv%7E0RzpZDdPMtfkrEas3W9bLUTfE0BlxY5ilvpcHDSuAFwtQk6MP0AlzLSiqzQQCc0Bj93rn6F%7EG0VKgkN8LAc6Z%7EYP3%7E2ZtuWo5KuoUsqXujB7UnzZTlrW3ZR5ODVWUB%7Ed6AWHlh7KLtczSKJTtLaC6vBOE0Tt9XFwX0sFazctlizlf-s6AQn26tMi0WryOQVXvrOGg__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1361551944476193
Resolving download.llamameta.net (download.llamameta.net)... 108.138.51.32, 108.138.51.79, 108.138.51.128, ...
Connecting to download.llamameta.net (download.llamameta.net)|108.138.51.32|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-20 23:25:34 ERROR 403: Forbidden.

--2023-11-20 23:25:34--  https://download.llamameta.net//checklist.chk?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoid2p5eTF5YjQwZDRxYXJwZWc5ZXhxaHE2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMDQ5OTQxM319fV19&Signature=PHLzzsM%7EBsX9EzzxAH1MbEzQjBWoMf4OM%7Eb7M0-auOub1jEBXL8X3xbJx24uaKGrCC-6VLPyjqpReHVcRkNOt6IH543eeypZwAgSH9io7P-Q-JQGKjHaXYjgD0A8n6330VRC07wQGC9VU1Lv%7E0RzpZDdPMtfkrEas3W9bLUTfE0BlxY5ilvpcHDSuAFwtQk6MP0AlzLSiqzQQCc0Bj93rn6F%7EG0VKgkN8LAc6Z%7EYP3%7E2ZtuWo5KuoUsqXujB7UnzZTlrW3ZR5ODVWUB%7Ed6AWHlh7KLtczSKJTtLaC6vBOE0Tt9XFwX0sFazctlizlf-s6AQn26tMi0WryOQVXvrOGg__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1361551944476193
Resolving download.llamameta.net (download.llamameta.net)... 108.138.51.32, 108.138.51.79, 108.138.51.128, ...
Connecting to download.llamameta.net (download.llamameta.net)|108.138.51.32|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-20 23:25:34 ERROR 403: Forbidden.

Checking checksums
md5sum: checklist.chk: no properly formatted checksum lines found
```

Then, I used a script available in the LLaMA repository (https://github.com/facebookresearch/llama/blob/main/download.sh), which allowed me to correctly download the 7b model. However, after executing the "inference.py" command in the console, I ran into another issue that I'm unable to resolve. It seems to me that the problem might be related to the model weights, but I don't have the means to download others. Below is the error message:
```
E:\pytorch-llama-main>python inference.py
Loading checkpoint "llama-2-7b\consolidated.00.pth"
Loaded checkpoint in 4.49s
Traceback (most recent call last):
  File "E:\pytorch-llama-main\inference.py", line 155, in <module>
    model = LLaMA.build(
  File "E:\pytorch-llama-main\inference.py", line 32, in build
    model_args: ModelArgs = ModelArgs(
TypeError: __init__() got an unexpected keyword argument 'rope_theta'
```

**Comment by hkproj** [comment]
Hi @mietekrmd. You need to remove the "rope_theta" parameter from the JSON file of the model.

**Comment by mietekrmd** [comment]
I removed the parameter you mentioned from the `params.json` file in the `llama-2-7b` folder:
However, this caused another error:
```
E:\pytorch-llama-main>python inference.py
Loading checkpoint "llama-2-7b\consolidated.00.pth"
Loaded checkpoint in 4.44s
Traceback (most recent call last):
  File "E:\pytorch-llama-main\inference.py", line 155, in <module>
    model = LLaMA.build(
  File "E:\pytorch-llama-main\inference.py", line 40, in build
    tokenizer.load(tokenizer_path)
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.12\lib\site-packages\sentencepiece\__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.12\lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: unk is not defined.
```
At this point, I'm not sure how to resolve this issue.

**Comment by hkproj** [comment]
The problem is in [this line](https://github.com/hkproj/pytorch-llama/blob/067f8a37fe36ac8b52dca9cc6f2a2e8d6aa372d6/inference.py#L36): you need to pass the parameters of the JSON file by hand instead of using the "params" dictionary. Very probably the new weights downloaded form Meta are different from the ones I downloaded when coding LLaMA, so that is causing the compatibility problem.
